# Generated by Django 5.2.8 on 2025-11-19 02:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_sorteo', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('precio_numero', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cantidad_numeros', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('sorteada', 'Sorteada')], default='activa', max_length=20)),
                ('premio_principal', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rifas/')),
                ('numeros_por_usuario', models.PositiveIntegerField(default=10, help_text='Máximo de números que un usuario puede comprar', validators=[django.core.validators.MinValueValidator(1)])),
                ('numeros_generados', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_sorteo'], name='main_rifa_estado_85e3e2_idx'), models.Index(fields=['fecha_sorteo'], name='main_rifa_fecha_s_b8bc85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', max_length=20)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('telefono_comprador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del comprador')),
                ('nombre_comprador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del comprador')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='main.rifa')),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'ordering': ['rifa', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anuncio', models.DateTimeField(auto_now_add=True)),
                ('premio_entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('telefono_ganador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del ganador')),
                ('nombre_ganador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del ganador')),
                ('numero_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_ganados', to='main.numero')),
                ('rifa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='main.rifa')),
            ],
            options={
                'verbose_name': 'Ganador',
                'verbose_name_plural': 'Ganadores',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono del cliente')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('cantidad_numeros', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('codigo_transaccion', models.CharField(blank=True, max_length=50, unique=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otros', 'Otros')], default='efectivo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('numeros', models.ManyToManyField(related_name='transacciones', to='main.numero')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='main.rifa')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='numero',
            index=models.Index(fields=['rifa', 'estado'], name='main_numero_rifa_id_ec9445_idx'),
        ),
        migrations.AddIndex(
            model_name='numero',
            index=models.Index(fields=['telefono_comprador'], name='main_numero_telefon_0bea39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='numero',
            unique_together={('rifa', 'numero')},
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['telefono_cliente', 'estado'], name='main_transa_telefon_417615_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['codigo_transaccion'], name='main_transa_codigo__8f6f04_idx'),
        ),
    ]
